Write-Output "安装 适用于Windows 10 LTSC 2021的媒体扩展"
Write-Output ""
Write-Output "by GitHub @idhaname"
Write-Output "https://github.com/idhaname/LTSC2021-MediaExt"
Write-Output ""
Write-Output "【注意】此安装程序仅适用于64位版本的Windows。"
Write-Output "32位版本请打开install_x86.ps1安装。"
Write-Output ""
Write-Output "要开始安装，请按指示继续"
pause
Write-Output "AV1视频扩展..."
add-appxpackage "$PSScriptRoot\Microsoft.AV1VideoExtension_1.1.52851.0_x64__8wekyb3d8bbwe.Appx"
Write-Output "HEIF图像扩展..."
add-appxpackage "$PSScriptRoot\Microsoft.HEIFImageExtension_1.0.60431.0_neutral___8wekyb3d8bbwe.AppxBundle"
Write-Output "HEVC视频扩展..."
add-appxpackage "$PSScriptRoot\Microsoft.HEVCVideoExtensions_2.0.60532.0_neutral___8wekyb3d8bbwe.AppxBundle"
Write-Output "MPEG-2视频扩展..."
add-appxpackage "$PSScriptRoot\Microsoft.MPEG2VideoExtension_1.0.50901.0_x64__8wekyb3d8bbwe.Appx"
Write-Output "RAW图像扩展..."
add-appxpackage "$PSScriptRoot\Microsoft.RawImageExtension_2.0.60612.0_neutral___8wekyb3d8bbwe.AppxBundle"
Write-Output "VP9视频扩展..."
add-appxpackage "$PSScriptRoot\Microsoft.VP9VideoExtensions_1.0.52781.0_x64__8wekyb3d8bbwe.Appx"
Write-Output "Web媒体扩展..."
add-appxpackage "$PSScriptRoot\Microsoft.WebMediaExtensions_1.0.42192.0_neutral___8wekyb3d8bbwe.AppxBundle"
Write-Output "Webp图像扩展..."
add-appxpackage "$PSScriptRoot\Microsoft.WebpImageExtension_1.0.52351.0_x64__8wekyb3d8bbwe.Appx"
Write-Output "安装完成！"
pause
exit