Write-Output "安装 适用于Windows 10 LTSC 2021的媒体扩展"
Write-Output ""
Write-Output "by GitHub @idhaname"
Write-Output "https://github.com/idhaname/LTSC2021-MediaExt"
Write-Output ""
Write-Output "请确认您已安装VCLibs"
Write-Output "若您还没有安装VCLibs，请右击文件夹下的vclibs_<x86/x64>.ps1-使用PowerShell运行，根据提示安装"
Write-Output ""
Write-Output "若您完成了以上准备工作，要开始安装 适用于Windows 10 LTSC 2021的媒体扩展 ，请按指示继续"
pause
Write-Output "AV1视频扩展..."
add-appxpackage "$PSScriptRoot\Microsoft.AV1VideoExtension_1.1.62361.0_neutral_~_8wekyb3d8bbwe.AppxBundle"
Write-Output "HEIF图像扩展..."
add-appxpackage "$PSScriptRoot\Microsoft.HEIFImageExtension_1.0.63001.0_neutral_~_8wekyb3d8bbwe.AppxBundle"
Write-Output "HEVC视频扩展..."
add-appxpackage "$PSScriptRoot\Microsoft.HEVCVideoExtensions_2.0.61933.0_neutral_~_8wekyb3d8bbwe.AppxBundle"
Write-Output "MPEG-2视频扩展..."
add-appxpackage "$PSScriptRoot\Microsoft.MPEG2VideoExtension_1.0.61931.0_neutral_~_8wekyb3d8bbwe.AppxBundle"
Write-Output "RAW图像扩展..."
add-appxpackage "$PSScriptRoot\Microsoft.RawImageExtension_2.0.63182.0_neutral_~_8wekyb3d8bbwe.AppxBundle"
Write-Output "VP9视频扩展..."
add-appxpackage "$PSScriptRoot\Microsoft.VP9VideoExtensions_1.0.62911.0_neutral_~_8wekyb3d8bbwe.AppxBundle"
Write-Output "Web媒体扩展..."
add-appxpackage "$PSScriptRoot\Microsoft.WebMediaExtensions_1.0.62931.0_neutral_~_8wekyb3d8bbwe.AppxBundle"
Write-Output "Webp图像扩展..."
add-appxpackage "$PSScriptRoot\Microsoft.WebpImageExtension_1.0.62681.0_neutral_~_8wekyb3d8bbwe.AppxBundle"
Write-Output "安装完成！"
pause
exit